version: '2'
services:
  easy_ssb_pub:
    build: .
    environment:
      PUB_URL: "${PUB_URL}"
      HOME: "${HOME}"
      DEBUG: "${DEBUG}"
    ports:
      - "80:80"
      - "8008:8008"
      - "8007:8007"
    volumes:
      - $HOME/.ssb:/root/.ssb
    container_name: easy-ssb-pub
    mem_limit: 450M
    restart: unless-stopped
